import {BaseEntity, BaseInformation} from '@pnrng/json-form';


export class FormModel extends BaseEntity<number> {
  constructor(
    public organizationName?: string,
    public classificationTopic?: string,
    public classificationId?: number,
    public sexTopic?: string,
    public sexId?: number,
    public registerLocation?: Location,
    public registerLocationId?: number,
    public birthLocation?: Location,
    public birthLocationId?: number,
    public religionId?: number,
    public religionTopic?: string,
    public exReligionId?: number,
    public exReligionTopic?: string,
    public sectId?: number,
    public sectTopic?: string,
    public exSectId?: number,
    public exSectTopic?: string,
    public bloodTypeId?: number,
    public bloodTypeTopic?: string,
    public maritalStatusId?: number,
    public maritalStatusTopic?: string,
    public dutyServiceId?: number,
    public dutyServiceTopic?: string,
    public firstName?: string,
    public lastName?: string,
    public fatherName?: string,
    public birthDate?: string,
    public diedDate?: string,
    public identifyNumber?: string,
    public nationalNumber?: string,
    public exFirstName?: string,
    public exFamilyName?: string,
    public aliasFirstName?: string,
    public aliasLastName?: string,
    public protectorId?: number,
    public fileCode?: string,
    public userId?: number,
    public enabled?: boolean,
    public country?: BaseInformation[],
    public iranianNationality?: boolean,
    public fullName?: string,
    public birthCertificateSerialHeadNumber?: string,
    public birthCertificateSerialScript?: number,
    public birthCertificateSerialNumber?: string,
    public latinFirstName?: string,
    public latinLastName?: string,
    public motherName?: string,
    public height?: number,
    public weight?: number,
    public shapeNoseId?: number,
    public dossireNumber?: string,
    public statusDocumentId?: string,
    public hasAppendix?: boolean,
    public isConfirm?: boolean,
    public relatedTypeTopic?: string,
    public relatedTypeId?: number,
    public identifyDescription?: string,
    public description?: string,
    public isPublic?: boolean,
    public dutyServiceLocationId?: number,
    public dutyServiceLocation?: Location,
    public memberShipsTitle?: string,
    // @ts-ignore
    public identifyDocumentType?: EnumEntry | number | string,
    public identifyDocumentTypeIndex?: number,
    public identifyDocumentTypeTitle?: string,
    public identifyDocumentTypePersianTitle?: string,
    // @ts-ignore
    public inquiryPersonList?: Inquiry[],
    // @ts-ignore
    public inquiryPersonListBeforeMonth?: Inquiry[]
  ) {
    super();
  }
}
