import { BaseEntity } from "./baseEntity.model";

export class Organization extends BaseEntity<number> {

  constructor(public name?: string,
              public parentId?: number,
              public code?: string,
              public typeFormation?: any,
              public typeFormationIndex?: number,
              public typeFormationTitle?: string,
              public typeFormationPersianTitle?: string,
              public unitTypeId?: number,
              public unitTypeTopic?: string,
              public organizationLevelId?: number,
              public organizationLevelTitle?: string,
              public unitIdentityId?: number,
              public unitIdentityTopic?: string,
              public unitExampleId?: number,
              public unitExampleTopic?: string,
              public topPlaceDeputyId?: number,
              public topPlaceDeputyTopic?: string,
              public permissibleLimitsId?: number,
              public permissibleLimitsTopic?: string,
              public postOccupancyPercentage?: number,
              public protectionPlaceId?: number,
              public protectionPlaceTopic?: string,
              public requestOriginId?: number,
              public requestOriginTopic?: string,
              public organizationRowId?: number,
              public organizationRowTopic?: string,
              public establishmentDate?: Date,
              public organization_Code?: string,
              public virtualOrganization?: boolean,
              public isPrivateOrganization?: boolean,
              public statusUnit?: boolean,
              public formationPatternId?: number,
              public formationPatternTitle?: string,
              public formationRequestOperationId?: number,
              public isLock?: boolean,
              public hierarchyCode?: string,
              public isDeleted?: boolean,
              public historyId?: number,
              public fromDate?: Date,
              public toDate?: Date,
              public isActive?: boolean,
              public organizationPatternId?: number,
              public organizationPatternTitle?: string,
              public parentName?: string,
              public sepOrganizationId?: number,
              public sepOrganizationName?: string,
              public locationId?: number,
              public locationTitle?: string,
              public description?: string,
              public positionId?: number,
              public positionTopic?: string,
              public organizationTypeId?: number,
              public organizationTypeTopic?: string,
              public rankId?: number,
              public rankTopic?: string,
              public organizationRequestId?: number,
              public createdSepOrganization?: Date,
              public dedicatedUnit?: boolean,
              public formationId?: number,
  ) {
    super();
    this.virtualOrganization = true;
    this.isPrivateOrganization = true;
    this.statusUnit = true;
  }
}
