import { BaseEntity } from "./baseEntity.model";

export class Personnel extends BaseEntity<number> {

  constructor(
    public iranianNationality?: boolean,
    public firstName?: string,
    public lastName?: string,
    public fullName?: string,
    public nationalNumber?: string,
    public identifyNumber?: string,
    public personnelCode?: string,
    public fatherName?: string,
    public latinFirstName?: string,
    public latinLastName?: string,
    public exFirstName?: string,
    public exFamilyName?: string,
    public nickName?: string,
    public birthDate?: string,
    public birthLocationId?: number,
    public birthLocationTitle?: string,
    public registerLocationId?: number,
    public registerLocationTitle?: string,
    public height?: number,
    public weight?: number,
    public injuries?: number,
    public jobTitle?: string,
    public description?: string,
    public phone?: string,
    public mobile?: string,
    public classificationTopic?: string,
    public classificationId?: number,
    public membershipTypeTopic?: string,
    public membershipTypeId?: number,
    public maritalStatusTopic?: string,
    public maritalStatusId?: number,
    public dutyServiceTopic?: string,
    public dutyServiceId?: number,
    public religionTopic?: string,
    public religionId?: number,
    public exReligionTopic?: string,
    public exReligionId?: number,
    public citizenTopic?: string,
    public citizenId?: number,
    public citizen?: Location,
    public exCitizenTopic?: string,
    public exCitizenId?: number,
    public nationalityTopic?: string,
    public nationalityId?: number,
    public hairColorTopic?: string,
    public hairColorId?: number,
    public eyeColorTopic?: string,
    public eyeColorId?: number,
    public skinColorTopic?: string,
    public skinColorId?: number,
    public bloodTypeTopic?: string,
    public bloodTypeId?: number,
    public languageTopic?: string,
    public languageId?: number,
    public sexTopic?: string,
    public sexId?: number,
    public educationField?: string,
    public educationLevelTopic?: string,
    public educationLevelId?: number,
    public organizationName?: string,
    public digitalDossierStatusId?: number,
    public digitalDossierStatusTopic?: string,
    public digitalPhysicalNo?: number,
    public organizationId?: number,
    public organizationHCode?: string,
    public identityType?: number,
    public identityTypeTitle?: string,
    public identityTypePersianTitle?: string,
    public fileCode?: string,
    public userId?: number,
    public registerLocation?: Location,
    public birthLocation?: Location,
    public homeAddress?: string,
    public workLocation?: string,
    public postalCode?: string,
    public email?: string,
    public workAddress?: string,
    public workStateId?: string,
    public workStateTopic?: string,
    public workPhone?: string,
    public enabled?: boolean,
    public filter?: boolean, // used for search
    public confirmDigitalArchiveDate?: string,
    public entryDate?: string,
    public exitDate?: string,
    public updatedByFullName?: string,
    public createdByFullName?: string,
  ) {
    super();
  }
}
