export enum BaseInfoEnum {
  CLASSIFICATION                   = 1,
  SEX                              = 11,
  FILE_TYPE_ID                     = 68,
  OBJECT_TYPE                      = 92,
  FORENSIC_ACTION_TYPE             = 10302,
  UNITLEVEL_ID                     = 217,
  FORENSIC_BASE_INFO               = 93405,
  ORGANIZATION_TYPE_ID             = 31,
  FORENSIC_KALA_TYPE_ID            = 10303,
  ORIGIN_OF_REQUEST_ID             = 10307,
  FORENSIC_KALA_RECEIVE_STATUS_ID  = 10304,
  PRIORITY_ID                      = 10305,
  FILE_TYPE_RELATED_ITEMS          = 10309,
  FILE_TYPE_ACTIONS_LIST           = 10310,
  ALARM_TYPE_TOPIC                 = 10311,
  SOURCE_ALARM_TOPIC               = 10312,
  BASE_ALARM_ID                    = 10313,
  ALARM_TIME_ID                    = 10314,
  RECEIVER_ALARM_TOPIC             = 10315,
  INSPECTION_ACTION                = 6019,
  RELIGION                         = 1002,
  SECT                             = 5,
  DUTY_SERVICE                     = 4,
  BLOOD_TYPE                       = 9,
  MARITAL_STATUS                   = 3
}
