import { AuthModel, UserModel } from "@pnrng/json-form";

export const user:UserModel={
    "id": 1,
    "personnelId": 1,
    "firstName": "محمد",
    "lastName": "فضلعلی",
    "username": "admin",
    "enabled": true,
    "fullName": "محمد فضلعلی",
    "email": null,
    "visitedCount": 140,
    "lastVisitDate": null,
    "online": true,
    "admin": false,
    "verify": false,
    "authorities": [
      "ROLE_MENU_274",
      "ROLE_MENU_275",
      "ROLE_MENU_299",
      "ROLE_MENU_100002",
      "ROLE_MENU_51",
      "ROLE_MENU_273",
      "ROLE_MENU_30001",
      "ROLE_MENU_52",
      "ROLE_MENU_5005",
      "ROLE_MENU_1001",
      "ROLE_MENU_5004",
      "ROLE_MENU_5003",
      "ROLE_MENU_5025",
      "ROLE_MENU_5002",
      "ROLE_MENU_5024",
      "ROLE_MENU_5023",
      "ROLE_MENU_5000",
      "ROLE_MENU_5021",
      "ROLE_USER",
      "ROLE_MENU_5020",
      "ROLE_MENU_1004",
      "ROLE_MENU_5008",
      "ROLE_MENU_1002",
      "ROLE_MENU_5007",
      "ROLE_MENU_1003",
      "ROLE_MENU_5006",
      "ROLE_MENU_45",
      "ROLE_MENU_46",
      "ROLE_MENU_283",
      "ROLE_MENU_3035",
      "ROLE_MENU_5016",
      "ROLE_MENU_3036",
      "ROLE_MENU_5015",
      "ROLE_MENU_3033",
      "ROLE_MENU_5014",
      "ROLE_MENU_3034",
      "ROLE_MENU_5013",
      "ROLE_MENU_5012",
      "ROLE_MENU_5011",
      "ROLE_MENU_5010",
      "ROLE_MENU_5019",
      "ROLE_MENU_3037",
      "ROLE_MENU_5018",
      "ROLE_MENU_3038",
      "ROLE_MENU_5017"
    ],
    "fileCode": "f1f7ae9b-d679-4745-b680-9e102aabfdcc",
    "organizationId": null,
    "organizationName": null,
    "personnelFileCode": "7dbd88f7-cd8a-4cfb-8918-836b54682bc8",
    "personnelNationalNumber": "2420116739",
    "userRoles": [
      {
        "id": 7,
        "version": null,
        "createdDate": "1398/03/25 20:8:4",
        "updatedDate": "1398/03/25 20:8:4",
        "roleId": 16,
        "roleTitle": "سرپرست سیستم",
        "userId": 1,
        "username": "محمد کریمی",
        "isCurrent": null,
        "groupId": 182,
        "groupName": "کاربان سامانه"
      }
    ],
    "roleTitle": null,
    "roleId": null,
    "groupTitle": null,
    "groupId": null,
    "classificationId": 1,
    "classificationTopic": "محرمانه",
    "failedAttempt": 0,
    password: '',
    pic: '',
    roles: [],
    occupation: '',
    companyName: '',
    phone: '',
    firstname: '',
    lastname: '',
    website: '',
    language: '',
    timeZone: '',
    setUser: function (_user: unknown): void {
      throw new Error('Function not implemented.');
    },
    authToken: '',
    refreshToken: '',
    expiresIn: undefined,
    setAuth: function (auth: AuthModel): void {
      throw new Error('Function not implemented.');
    }
  }
